# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: nova-os
description: Custom Aurora image with Niri, Ghostty, dev tools, and curated apps

base-image: ghcr.io/ublue-os/aurora
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        - che/zed
        - iucar/rstudio
    install:
      packages:
        - niri
        - nautilus
        - R
        - rstudio-desktop
        - zed
        - ghostty
        
    remove:
      packages:
        - kate
        - ptyxis

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.github.wwmm.easyeffects
          - re.sonny.Eloquent
          - org.equicord.equibop
          - io.gitlab.librewolf-community
          - io.github.juancarlosbernal.FolderPlay
          - org.inkscape.Inkscape
          - org.videolan.VLC
          - org.gnome.Maps
          - com.obsproject.Studio
          - me.proton.Mail
          - me.proton.Pass
          - org.qbittorrent.qBittorrent
          - com.spotify.Client
          - com.valvesoftware.Steam
          - dev.mufeed.Wordbook
          - io.missioncenter.MissionCenter
          - org.gnome.gitlab.somas.Apostrophe
        remove:
          - org.kde.kontact
          - org.mozilla.Thunderbird
          - org.kde.kcalc
          - org.kde.kweather
          - org.deskflow.deskflow
          - org.fedoraproject.MediaWriter

  - type: signing